#!/bin/bash

function src()
{
    source $(dirname $0)/inc/$1
}

src functions.sh

function setup()
{
    #TODO check for tmux
    export TERM=tmux
    if [ -z $TMUX ] ; then
        echo "You need to run the Connection Manager inside TMux, lemme start it for you"
        tmux new-session -n "CM" "$0 $*"
        exit $?
    fi
}

function CM_1()
{
    dia --inputbox "Test" 0 0
}

function main()
{
    setup
    menu "CM" \
        "1" "Connect to the network"

    #case $DRET in
    #    1) echo "Connect to the Internet woo hoo"
    #       read
    #        ;;
    #esac
}

main
