#!/bin/bash

#Some config
DEF_LAN_DEV="enp0s31f6"
DEF_WLAN_DEV="wlp4s0"

#So we won't expose the extra files on the PATH
function src()
{
    source $(dirname $0)/inc/$1
}

src "functions.sh"
src "ifsmenu.sh"
src "connectmenu.sh"
src "mainmenu.sh"

function setup()
{
    #TODO check for tmux
    export TERM=tmux
    if [ -z $TMUX ] ; then
        echo "You need to run the Connection Manager inside TMux, lemme start it for you"
        tmux new-session -n "CM" "$0 $*"
        exit $?
    fi
}

function main()
{
    setup
    while [ 1 ] ; do
        mainmenu
        if [ $? -ne 0 ] ; then
            break
        fi
    done
    #case $DRET in
    #    1) echo "Connect to the Internet woo hoo"
    #       read
    #        ;;
    #esac
}

main

#cleanup
tmux kill-pane -a
