#!/bin/bash

WIFI_CONF_DIR="$HOME/.cm/wifi"
VPN_CONF_DIR="$HOME/.cm/vpn"
NAMESPACE="Default"
TEMPDIR="/tmp/cm"
RECDIR="$HOME/.cm/rec"
WIFI_OTA_DIR="$HOME/temp"

mkdir -p $TEMPDIR
mkdir -p $RECDIR
mkdir -p $WIFI_CONF_DIR
mkdir -p $VPN_CONF_DIR
mkdir -p $WIFI_OTA_DIR

#So we won't expose the extra files on the PATH

DIALOGRC=$(dirname $0)/dialog.conf
function src()
{
    source $(dirname $0)/inc/$1
}

src "functions.sh"
src "ifsmenu.sh"
src "connectmenu.sh"
src "mainmenu.sh"
src "wifimenu.sh"
src "ssidmenu.sh"
src "nsmenu.sh"
src "vlanmenu.sh"
src "vpnmenu.sh"
src "ipmenu.sh"
src "vethmenu.sh"
src "recmenu.sh"
src "l2menu.sh"
src "brmenu.sh"
src "tapmenu.sh"

function setup()
{
    #TODO check for tmux
    export TERM=tmux
    if [ -z $TMUX ] ; then
        echo "You need to run the Connection Manager inside TMux, lemme start it for you"
        tmux new-session -n "CM" "$0 $*"
        exit $?
    fi
}

function main()
{
    setup
    while [ 1 ] ; do
        mainmenu
        if [ $? -ne 0 ] ; then
            break
        fi
    done
}

main

#echo "Dead jim... dead."
#read
#cleanup
tmux kill-session
